title: "Chart-Log"
description: "株式チャート解析の記録サイト"
url: "https://mizuki020.github.io"
baseurl: "/chart-log"           # ← リポジトリ名に合わせる
lang: ja

# これが“最速”のキモ：ローカル不要でテーマ適用
remote_theme: jeffreytse/jekyll-theme-yat

# 便利系（GitHub Pages公式サポート）
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# YATの基本設定（必要に応じて後で調整）
yat:
  date_format: "%Y-%m-%d"
  show_author_profile: false
  toc:
    enable: true
    max_depth: 3
navbar:
  - title: ホーム
    url: /
  - title: 銘柄一覧
    url: /tickers/
  - title: 9983
    url: /9983/
  - title: 6758
    url: /6758/
  - title: 8058
    url: /8058/

# パーマリンク：/9983/2025-08-29/ 形式に合わせる
permalink: /:categories/:year-:month-:day/
